// Central product data source
export const PRODUCTS = [
  {
    id: 'casement',
    name: 'Casement Window',
    tag: 'Best Seller',
    tagColor: 'green',
    shortDesc: 'Outward-opening window with airtight seal. Ideal for ventilation and unobstructed views.',
    longDesc: `The ClearView Casement Window combines European engineering with the demands of the Indian climate. Its outward-opening design creates a natural air scoop that funnels fresh air directly into your space, while the multi-point locking system provides exceptional security.

The double-sealed rebate design prevents water ingress even in heavy monsoon conditions, while the thermally broken frame dramatically reduces heat transfer — keeping your interiors cooler in summer and warmer in winter.`,
    basePrice: 8500,
    unit: '/ sq.ft',
    material: 'German uPVC Profile (VEKA / Schüco)',
    profileSeries: '70mm 3-chamber',
    thicknessMm: 28,
    features: ['Double glazed', 'Multi-point lock', 'Weather strip seal', 'Tilt & turn option', 'Child safety lock', 'Mosquito mesh'],
    specs: {
      'Profile Depth': '70mm',
      'Glass Thickness': '4+12+4mm (IGU)',
      'Max Width': '1500mm',
      'Max Height': '2000mm',
      'U-Value': '1.4 W/m²K',
      'Sound Reduction': '32 dB',
      'Wind Load': 'Class C4',
      'Water Tightness': 'Class E750',
    },
    colors: ['White', 'Anthracite Grey', 'Golden Oak', 'Dark Brown', 'Racing Green', 'Navy Blue'],
    galleryImages: 4,
    warranty: '10 Years',
    category: 'window',
    popular: true,
  },
  {
    id: 'sliding',
    name: 'Sliding Window',
    tag: 'Popular',
    tagColor: 'blue',
    shortDesc: 'Smooth horizontal sliding sash for large openings. Perfect for balconies and living rooms.',
    longDesc: `The ClearView Sliding Window is engineered for wide openings where a casement would be impractical. Stainless steel roller bearings ensure silky-smooth operation year after year, even in dusty or coastal environments.

The anti-lift device prevents unauthorized removal of the sash from outside, while the dual-weather seal prevents dust and water ingress — a critical feature in coastal Tamil Nadu climates.`,
    basePrice: 7200,
    unit: '/ sq.ft',
    material: 'Schüco Profile System',
    profileSeries: '60mm 2-track',
    thicknessMm: 24,
    features: ['Anti-lift device', 'SS roller bearings', 'Mosquito mesh included', 'Double weather seal', 'Powder-coated hardware', 'Easy-clean design'],
    specs: {
      'Profile Depth': '60mm',
      'Glass Thickness': '5mm toughened',
      'Max Width': '3000mm',
      'Max Height': '1800mm',
      'U-Value': '2.0 W/m²K',
      'Sound Reduction': '28 dB',
      'Track Type': '2-track / 3-track',
      'Hardware': 'Stainless Steel 304',
    },
    colors: ['White', 'Dark Grey', 'Bronze', 'Cream', 'Ivory'],
    galleryImages: 3,
    warranty: '10 Years',
    category: 'window',
    popular: true,
  },
  {
    id: 'french-door',
    name: 'French Door',
    tag: 'Premium',
    tagColor: 'amber',
    shortDesc: 'Elegant double-leaf door with full-height glass panels bringing light and luxury.',
    longDesc: `The ClearView French Door transforms any room into a statement of refined taste. Twin full-height glass panels flood interiors with natural light while the 180-degree opening creates a seamless passage between spaces.

Triple-point locking on each leaf ensures exceptional security, while the thermally broken frame and double glazing maintain comfortable interior temperatures. The concealed hinges and flush threshold complete the luxury aesthetic.`,
    basePrice: 32000,
    unit: '/ pair',
    material: 'Rehau uPVC System (GENEO)',
    profileSeries: '86mm 6-chamber',
    thicknessMm: 44,
    features: ['Triple-point locking', '180° full opening', 'Thermal break frame', 'Safety toughened glass', 'Concealed hinges', 'Flush threshold'],
    specs: {
      'Profile Depth': '86mm',
      'Glass Thickness': '6+16+6mm triple glaze',
      'Max Width': '2400mm (pair)',
      'Max Height': '2500mm',
      'U-Value': '0.9 W/m²K',
      'Sound Reduction': '42 dB',
      'Security': 'RC2 burglar resistant',
      'Threshold': 'Accessible flush',
    },
    colors: ['White', 'Anthracite Black', 'Golden Oak', 'Agate Grey', 'Custom RAL'],
    galleryImages: 5,
    warranty: '10 Years',
    category: 'door',
    popular: true,
  },
  {
    id: 'liftslide',
    name: 'Lift & Slide Door',
    tag: 'Luxury',
    tagColor: 'purple',
    shortDesc: 'Large-format sliding door with effortless lift mechanism for indoor-outdoor living.',
    longDesc: `The ClearView Lift & Slide Door redefines large-format openings. The precision-engineered lift mechanism raises the panel off its seal for feather-light sliding, then drops it back into an airtight seal when closed.

Available in widths up to 6 meters and heights up to 2.8 meters, this door is the defining feature of luxury homes seeking seamless indoor-outdoor connectivity. Optional integrated blinds and triple glazing make it as functional as it is breathtaking.`,
    basePrice: 58000,
    unit: '/ panel',
    material: 'Internorm KF500 Profile',
    profileSeries: '92mm 7-chamber',
    thicknessMm: 52,
    features: ['Lift-slide mechanism', 'Up to 6m width', 'Integrated blind option', 'Triple acoustic glass', 'Flush floor rail', 'Child-safe operation'],
    specs: {
      'Profile Depth': '92mm',
      'Glass Thickness': '8+20+8mm triple',
      'Max Width': '6000mm',
      'Max Height': '2800mm',
      'U-Value': '0.7 W/m²K',
      'Sound Reduction': '48 dB',
      'Sliding Force': '< 30N (feather touch)',
      'Weight Capacity': 'Up to 400kg/panel',
    },
    colors: ['White', 'Anthracite', 'Agate Grey', 'Jet Black', 'Custom RAL'],
    galleryImages: 4,
    warranty: '10 Years',
    category: 'door',
    popular: false,
  },
  {
    id: 'bay',
    name: 'Bay Window',
    tag: 'Design Statement',
    tagColor: 'teal',
    shortDesc: 'Projecting three-panel window that maximizes light and creates usable interior space.',
    longDesc: `The ClearView Bay Window is a transformative architectural feature that projects from the exterior wall, creating a bay of natural light and additional interior space. The three-panel configuration — typically a fixed central panel with opening side lights — floods rooms with panoramic views.

Custom-manufactured steel structural support is concealed within the uPVC frame, ensuring the bay is as structurally sound as it is beautiful. A cushioned window seat in the bay becomes the most loved spot in any home.`,
    basePrice: 24000,
    unit: '/ unit',
    material: 'VEKA Softline 82 Profile',
    profileSeries: '82mm 5-chamber',
    thicknessMm: 36,
    features: ['3-panel design', 'Hidden structural steel', 'Custom projection angles', 'Weatherproof corner joins', 'Integral window seat option', 'Double glazed throughout'],
    specs: {
      'Profile Depth': '82mm',
      'Glass Thickness': '4+14+4mm (IGU)',
      'Projection': '300–600mm',
      'Typical Width': '1800–3000mm',
      'Angles': '25° / 35° / 45° bay',
      'U-Value': '1.2 W/m²K',
      'Structural Support': 'Galvanized steel',
      'Lead Time': '4–6 weeks',
    },
    colors: ['White', 'Cream', 'Anthracite Grey', 'Golden Oak', 'Sage Green'],
    galleryImages: 3,
    warranty: '10 Years',
    category: 'window',
    popular: false,
  },
  {
    id: 'tilt-turn',
    name: 'Tilt & Turn Window',
    tag: 'Versatile',
    tagColor: 'green',
    shortDesc: 'Dual-function window: tilt inward for ventilation or turn fully for cleaning and maximum airflow.',
    longDesc: `The ClearView Tilt & Turn Window is the most versatile window in our range. A single handle controls two distinct opening modes: tilt the sash inward from the top for controlled, draught-free ventilation even in rain; or turn it fully open like a casement for maximum airflow and easy external cleaning.

The child-safety restrictor locks the tilt-only mode when young children are present. The same multi-point locking system used in our French Doors ensures maximum security in the closed position.`,
    basePrice: 9800,
    unit: '/ sq.ft',
    material: 'Salamander Streamline Profile',
    profileSeries: '76mm 4-chamber',
    thicknessMm: 32,
    features: ['Tilt-only ventilation', 'Full-turn opening', 'Child safety restrictor', 'Burglar-proof class RC1', 'Easy external cleaning', 'Rain-proof tilt mode'],
    specs: {
      'Profile Depth': '76mm',
      'Glass Thickness': '4+16+4mm (IGU)',
      'Max Width': '1200mm',
      'Max Height': '1600mm',
      'U-Value': '1.3 W/m²K',
      'Sound Reduction': '34 dB',
      'Hardware': 'Roto NT multipoint',
      'Child Lock': 'Integrated restrictor',
    },
    colors: ['White', 'Anthracite', 'Dark Brown', 'Cream', 'Agate Grey'],
    galleryImages: 3,
    warranty: '10 Years',
    category: 'window',
    popular: false,
  },
]

// Pricing multipliers
export const GLASS_OPTIONS = [
  { value: 'clear',   label: 'Clear Double Glazed',   addPrice: 0,    opacity: 0.32, color: '#b8ddd4', desc: 'Standard 4+12+4mm IGU' },
  { value: 'tinted',  label: 'Bronze Tinted',          addPrice: 1500, opacity: 0.45, color: '#8B6914', desc: 'Solar heat reduction 35%' },
  { value: 'frosted', label: 'Frosted Privacy',        addPrice: 2000, opacity: 0.72, color: '#d4e8e4', desc: 'Full privacy, diffused light' },
  { value: 'solar',   label: 'Solar Control Low-E',    addPrice: 4500, opacity: 0.5,  color: '#4a6670', desc: 'Best energy performance' },
  { value: 'triple',  label: 'Triple Glazed Acoustic', addPrice: 7000, opacity: 0.28, color: '#9ecec8', desc: 'Up to 48dB sound reduction' },
]

export const COLOR_OPTIONS = [
  { name: 'White',          hex: '#F8F8F8', addPrice: 0    },
  { name: 'Anthracite Grey',hex: '#3C3C3C', addPrice: 1200 },
  { name: 'Golden Oak',     hex: '#8B6914', addPrice: 2500 },
  { name: 'Dark Brown',     hex: '#4a2c0a', addPrice: 2000 },
  { name: 'Racing Green',   hex: '#1F7A63', addPrice: 1200 },
  { name: 'Navy Blue',      hex: '#1E3A5F', addPrice: 1200 },
  { name: 'Agate Grey',     hex: '#888B8D', addPrice: 800  },
  { name: 'Jet Black',      hex: '#1a1a1a', addPrice: 1500 },
]

// AI recommendation logic
export const AI_SUGGESTIONS = {
  bedroom: {
    economy:  { id: 'tilt-turn',     reason: 'Tilt mode gives draught-free overnight ventilation with full security — perfect for bedrooms.' },
    mid:      { id: 'casement',      reason: 'Airtight casement with double glazing for quiet, thermally comfortable sleep.' },
    premium:  { id: 'bay',           reason: 'A bay window creates a stunning reading nook while flooding the bedroom with natural light.' },
    luxury:   { id: 'bay',           reason: 'Full bay system with window seat and blackout-blind integrated into the frame.' },
  },
  living: {
    economy:  { id: 'sliding',       reason: 'Wide-span sliding for maximum views and ventilation in living areas.' },
    mid:      { id: 'casement',      reason: 'Superior insulation and security over sliding — ideal for a comfortable family living room.' },
    premium:  { id: 'french-door',   reason: 'French doors flood the living room with light and create an elegant flow to the outdoors.' },
    luxury:   { id: 'liftslide',     reason: 'The ultimate living room statement — seamless indoor-outdoor connection with one touch.' },
  },
  kitchen: {
    economy:  { id: 'sliding',       reason: 'Easy single-hand operation and moisture-resistant profile for kitchen environments.' },
    mid:      { id: 'casement',      reason: 'Opens fully to expel cooking fumes; easy to clean from inside.' },
    premium:  { id: 'casement',      reason: 'Solar-control glass keeps kitchen cooler in Indian summers; easy clean coating.' },
    luxury:   { id: 'liftslide',     reason: 'A bi-fold or lift-slide opening creates an open-plan kitchen-garden connection.' },
  },
  bathroom: {
    economy:  { id: 'sliding',       reason: 'Frosted sliding window for privacy with good ventilation.' },
    mid:      { id: 'tilt-turn',     reason: 'Tilt mode provides continuous ventilation without compromising privacy or security.' },
    premium:  { id: 'tilt-turn',     reason: 'Frosted tilt-turn with integrated ventilation grille for moisture-heavy bathrooms.' },
    luxury:   { id: 'casement',      reason: 'Floor-level opaque casement with automated opener for a spa-like private bathroom.' },
  },
  office: {
    economy:  { id: 'tilt-turn',     reason: 'Tilt ventilation keeps you focused; secure when unattended.' },
    mid:      { id: 'casement',      reason: 'Solar-control glass reduces screen glare and AC costs in a south-facing office.' },
    premium:  { id: 'casement',      reason: 'Acoustic double glazing with solar-E coating — quiet, cool, and professional.' },
    luxury:   { id: 'liftslide',     reason: 'Floor-to-ceiling lift-slide creates an executive office that opens onto a private terrace.' },
  },
  balcony: {
    economy:  { id: 'sliding',       reason: 'Smooth sliding panels close the balcony for monsoon protection when needed.' },
    mid:      { id: 'french-door',   reason: 'French doors frame the balcony elegantly and open fully on dry days.' },
    premium:  { id: 'liftslide',     reason: 'Lift-slide creates a glazed balcony that can be fully opened or sealed seasonally.' },
    luxury:   { id: 'liftslide',     reason: 'Full-wall lift-slide system transforms the balcony into a seamless indoor-outdoor lounge.' },
  },
}

export const TESTIMONIALS = [
  { name: 'Rajesh Kumar', location: 'Chennai, Tamil Nadu', rating: 5, text: 'The sliding windows from ClearView transformed our living room completely. Excellent insulation — our AC bills dropped 30% after installation. The team was professional from measurement to the final clean-up.', initials: 'RK' },
  { name: 'Priya Suresh', location: 'Coimbatore, Tamil Nadu', rating: 5, text: "Their 3D configurator let me visualize exactly how the French doors would look in my living room before I committed. Saved me from a colour mistake. The installation was immaculate — completed in one day.", initials: 'PS' },
  { name: 'Arjun Menon', location: 'Kanyakumari, Tamil Nadu', rating: 4, text: "Best value for money in the uPVC market. The casement windows handle the coastal winds here brilliantly — no rattling, no rust, no leaks even in the monsoon. My neighbour has already placed an order.", initials: 'AM' },
  { name: 'Sunita Balasubramanian', location: 'Madurai, Tamil Nadu', rating: 5, text: "We replaced 14 windows across our villa. ClearView managed the entire project — survey, manufacture, and installation — with zero hassle. The house is noticeably quieter now.", initials: 'SB' },
  { name: 'Karthik Rajan', location: 'Trichy, Tamil Nadu', rating: 5, text: "The bay window in our master bedroom is the centrepiece of the house. The structural support is hidden within the frame and the finish is flawless. Guests always comment on it.", initials: 'KR' },
  { name: 'Meera Pillai', location: 'Tirunelveli, Tamil Nadu', rating: 5, text: "Responsive, reliable, and genuinely knowledgeable. When I wasn't sure between tilt-turn and casement, the site engineer spent 45 minutes explaining the pros and cons. No pressure, just honest advice.", initials: 'MP' },
]

export const GALLERY_ITEMS = [
  { title: 'Modern Villa Renovation', location: 'Boat Club Road, Chennai', category: 'Residential', products: 'Casement Windows × 12', year: '2024', cols: 2 },
  { title: 'Lakefront Apartment Complex', location: 'Coimbatore', category: 'Multi-Unit', products: 'Sliding Windows × 86', year: '2024', cols: 1 },
  { title: 'Private Beach House', location: 'Kanyakumari', category: 'Coastal', products: 'French Doors + Liftslide', year: '2023', cols: 1 },
  { title: 'Corporate HQ Lobby', location: 'Madurai IT Park', category: 'Commercial', products: 'Curtain Wall + Lift-Slide', year: '2024', cols: 2 },
  { title: 'Heritage Bungalow Upgrade', location: 'Chettinad', category: 'Restoration', products: 'Bay Windows × 4', year: '2023', cols: 1 },
  { title: 'Penthouse Terrace', location: 'OMR, Chennai', category: 'Luxury', products: 'Lift & Slide × 6m', year: '2024', cols: 1 },
]
